#!/usr/bin/env node
/**
 * One-shot extractor: derives `data/uploads.json` from the two places the
 * pre-refactor code listed accepted file types.
 *
 * WHY this matters more than it looks: the list appeared twice, in different
 * notations: once as the `accept` attribute on the file input
 * (`image/*,.txt,.java,...`) and once as a regex inside `isTextLikeFile`
 * (`/\.(txt|java|...)$/i`). The attribute decides what the OS file picker
 * shows; the regex decides what actually gets read into the code box. They
 * happened to agree, but nothing enforced that, so adding `.rs` to one and
 * forgetting the other would produce a file the picker offers and the app then
 * silently ignores, a bug with no error message anywhere.
 *
 * The script extracts both, asserts they are the same set, and emits one list.
 *
 * Usage: node scripts/extract-uploads.mjs
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

/** The last commit before the refactor began; the source of truth for behavior. */
export const BASELINE_REF = "ec79f2d";

function readBaseline(path) {
  return execFileSync("git", ["show", `${BASELINE_REF}:${path}`], {
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024,
  });
}

/** Extensions named in the `accept` attribute, minus the `image/*` wildcard. */
function parseAcceptAttribute(source) {
  const match = source.match(/accept="([^"]+)"/);
  if (!match) throw new Error("Could not find the file input's accept attribute");
  return {
    wildcards: match[1].split(",").filter((entry) => !entry.startsWith(".")),
    extensions: match[1]
      .split(",")
      .filter((entry) => entry.startsWith("."))
      .map((entry) => entry.slice(1)),
  };
}

/** Extensions named in the `isTextLikeFile` alternation. */
function parseTextFileRegex(source) {
  const match = source.match(/\/\\\.\(([a-z|]+)\)\$\/i/);
  if (!match) throw new Error("Could not find the isTextLikeFile extension regex");
  return match[1].split("|");
}

export function extractUploads() {
  const page = readBaseline("app/page.tsx");
  const accept = parseAcceptAttribute(page);
  const fromRegex = parseTextFileRegex(page);

  const onlyInAccept = accept.extensions.filter((e) => !fromRegex.includes(e));
  const onlyInRegex = fromRegex.filter((e) => !accept.extensions.includes(e));
  if (onlyInAccept.length || onlyInRegex.length) {
    throw new Error(
      "The accept attribute and isTextLikeFile disagree; collapsing them " +
        `would change behavior. Only in accept: [${onlyInAccept}]; ` +
        `only in regex: [${onlyInRegex}]`,
    );
  }

  return {
    $comment:
      "Generated by scripts/extract-uploads.mjs. Add a language by appending " +
      "its extension to textExtensions; it feeds both the file picker's " +
      "accept attribute and the drop handler's text-file detection.",
    // Kept in the original order so the file picker's dropdown is unchanged.
    textExtensions: accept.extensions,
    // Mirrors the original attribute, which also accepted any image type.
    imageAcceptWildcards: accept.wildcards,
  };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const data = extractUploads();
  writeFileSync(
    new URL("../data/uploads.json", import.meta.url),
    `${JSON.stringify(data, null, 2)}\n`,
  );
  console.log(
    `Wrote data/uploads.json (${data.textExtensions.length} text extensions, ` +
      `wildcards: ${data.imageAcceptWildcards.join(", ")})`,
  );
}
