#!/usr/bin/env node
/**
 * One-shot extractor: lifts the four custom-property blocks out of the
 * pre-refactor globals.css into `data/theme.json`.
 *
 * WHY: the palette was defined four times — a `:root` block, a
 * `@media (prefers-color-scheme: light)` override, and then `:root.theme-dark`
 * and `:root.theme-light` blocks 1180 lines further down that restate most of
 * the same variables for the manual toggle. Retuning the accent colour meant
 * finding all four and knowing which ones actually win. As JSON the palettes
 * sit side by side and can be diffed at a glance.
 *
 * Usage: node scripts/extract-theme.mjs
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

/** The last commit before the refactor began; the source of truth for behavior. */
export const BASELINE_REF = "ec79f2d";

/**
 * The four blocks, in the order they appeared.
 *
 * Order is preserved because `:root` and the `prefers-color-scheme` override
 * have equal specificity, so only source order decides between them. The two
 * `:root.theme-*` blocks carry an extra class and therefore win over both
 * regardless of where they sit — which is what makes the manual toggle
 * override the OS preference.
 */
const BLOCKS = [
  { key: "base", selector: ":root", media: null },
  { key: "systemLight", selector: ":root", media: "(prefers-color-scheme: light)" },
  { key: "dark", selector: ":root.theme-dark", media: null },
  { key: "light", selector: ":root.theme-light", media: null },
];

function readBaselineCss() {
  return execFileSync("git", ["show", `${BASELINE_REF}:app/globals.css`], {
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024,
  });
}

/** Strips `/* ... *\/` comments so they are not mistaken for values. */
function stripComments(text) {
  return text.replace(/\/\*[\s\S]*?\*\//g, "");
}

/**
 * Parses `--name: value;` declarations out of a block body, keeping source
 * order — CSS custom properties can reference each other, and reordering them
 * would be a silent behavior change.
 */
function parseDeclarations(body) {
  const declarations = {};
  for (const [, name, value] of stripComments(body).matchAll(
    /(--[a-z0-9-]+)\s*:\s*([^;]+);/gi,
  )) {
    declarations[name] = value.trim().replace(/\s+/g, " ");
  }
  return declarations;
}

/** Finds a block's body by brace-matching from its opening `{`. */
function blockBody(css, startIndex) {
  const open = css.indexOf("{", startIndex);
  if (open === -1) throw new Error("Unterminated block");
  let depth = 0;
  for (let i = open; i < css.length; i += 1) {
    if (css[i] === "{") depth += 1;
    else if (css[i] === "}") {
      depth -= 1;
      if (depth === 0) return css.slice(open + 1, i);
    }
  }
  throw new Error("Unterminated block");
}

export function extractTheme() {
  const css = readBaselineCss();
  const palettes = {};

  for (const { key, selector, media } of BLOCKS) {
    let searchFrom = 0;
    if (media) {
      const mediaIndex = css.indexOf(`@media ${media}`);
      if (mediaIndex === -1) throw new Error(`Could not find @media ${media}`);
      searchFrom = mediaIndex;
    }
    // Anchor on the selector followed by optional whitespace and a brace, so
    // `:root` does not accidentally match inside `:root.theme-dark`.
    const pattern = new RegExp(`${selector.replace(/[.]/g, "\\.")}\\s*\\{`);
    const relative = css.slice(searchFrom).search(pattern);
    if (relative === -1) throw new Error(`Could not find ${selector}`);
    const declarations = parseDeclarations(blockBody(css, searchFrom + relative));
    if (Object.keys(declarations).length === 0) {
      throw new Error(`${selector} produced no custom properties`);
    }
    palettes[key] = { selector, media, tokens: declarations };
  }

  return {
    $comment:
      "Generated by scripts/extract-theme.mjs. Edit a colour here and run " +
      "`npm run generate:tokens` to rebuild app/styles/tokens.generated.css. " +
      "Block order is significant: `base` and `systemLight` have equal " +
      "specificity so only source order separates them.",
    palettes,
  };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const data = extractTheme();
  writeFileSync(
    new URL("../data/theme.json", import.meta.url),
    `${JSON.stringify(data, null, 2)}\n`,
  );
  const counts = Object.entries(data.palettes)
    .map(([key, block]) => `${key}: ${Object.keys(block.tokens).length}`)
    .join(", ");
  console.log(`Wrote data/theme.json (${counts})`);
}
